CLASSES=\
	org.vngx.jsch.algorithm.Algorithm	\
	org.vngx.jsch.algorithm.AlgorithmFactory	\
	org.vngx.jsch.algorithm.AlgorithmManager	\
	org.vngx.jsch.algorithm.Algorithms	\
	org.vngx.jsch.algorithm.Compression	\
	org.vngx.jsch.algorithm.CompressionImpl	\
	org.vngx.jsch.algorithm.DefaultAlgorithmFactory	\
	org.vngx.jsch.algorithm.KeyPairGenDSA	\
	org.vngx.jsch.algorithm.KeyPairGenDSAImpl	\
	org.vngx.jsch.algorithm.KeyPairGenRSA	\
	org.vngx.jsch.algorithm.KeyPairGenRSAImpl	\
	org.vngx.jsch.algorithm.Random	\
	org.vngx.jsch.algorithm.RandomImpl	\
	org.vngx.jsch.algorithm.SignatureDSA	\
	org.vngx.jsch.algorithm.SignatureDSAImpl	\
	org.vngx.jsch.algorithm.SignatureRSA	\
	org.vngx.jsch.algorithm.SignatureRSAImpl	\
	org.vngx.jsch.algorithm.UnsupportedAlgorithmException	\
	org.vngx.jsch.Buffer	\
	org.vngx.jsch.Channel	\
	org.vngx.jsch.ChannelAgentForwarding	\
	org.vngx.jsch.ChannelDirectTCPIP	\
	org.vngx.jsch.ChannelExec	\
	org.vngx.jsch.ChannelForwardedTCPIP	\
	org.vngx.jsch.ChannelSession	\
	org.vngx.jsch.ChannelSftp	\
	org.vngx.jsch.ChannelShell	\
	org.vngx.jsch.ChannelSubsystem	\
	org.vngx.jsch.ChannelType	\
	org.vngx.jsch.ChannelX11	\
	org.vngx.jsch.cipher.Cipher	\
	org.vngx.jsch.cipher.CipherException	\
	org.vngx.jsch.cipher.CipherImpl	\
	org.vngx.jsch.cipher.CipherManager	\
	org.vngx.jsch.cipher.CipherNone	\
	org.vngx.jsch.config.BooleanPropertyValidator	\
	org.vngx.jsch.config.InvalidPropertyException	\
	org.vngx.jsch.config.JSchConfig	\
	org.vngx.jsch.config.NumberPropertyValidator	\
	org.vngx.jsch.config.PropertyValidator	\
	org.vngx.jsch.config.SessionConfig	\
	org.vngx.jsch.config.SSHConfigConstants	\
	org.vngx.jsch.config.StringSetPropertyValidator	\
	org.vngx.jsch.constants.ConnectionProtocol	\
	org.vngx.jsch.constants.MessageConstants	\
	org.vngx.jsch.constants.SftpProtocol	\
	org.vngx.jsch.constants.SSHConstants	\
	org.vngx.jsch.constants.TransportLayerProtocol	\
	org.vngx.jsch.constants.UserAuthProtocol	\
	org.vngx.jsch.exception.JSchException	\
	org.vngx.jsch.exception.SftpException	\
	org.vngx.jsch.ForwardedTCPIPDaemon	\
	org.vngx.jsch.hash.Hash	\
	org.vngx.jsch.hash.HashImpl	\
	org.vngx.jsch.hash.HashManager	\
	org.vngx.jsch.hash.MAC	\
	org.vngx.jsch.hash.MACException	\
	org.vngx.jsch.hash.MACImpl	\
	org.vngx.jsch.hash.MACImplAlternate	\
	org.vngx.jsch.IO	\
	org.vngx.jsch.JSch	\
	org.vngx.jsch.kex.AbstractDHKexAlgorithm	\
	org.vngx.jsch.kex.DHGexSha1KexAlgorithm	\
	org.vngx.jsch.kex.DHGexSha256KexAlgorithm	\
	org.vngx.jsch.kex.DHGroup14KexAlgorithm	\
	org.vngx.jsch.kex.DHGroup1KexAlgorithm	\
	org.vngx.jsch.kex.DHGroupKexAlgorithm	\
	org.vngx.jsch.kex.DiffieHellman	\
	org.vngx.jsch.kex.DiffieHellmanImpl	\
	org.vngx.jsch.kex.KexAlgorithm	\
	org.vngx.jsch.kex.KexException	\
	org.vngx.jsch.kex.KexProposal	\
	org.vngx.jsch.kex.KeyExchange	\
	org.vngx.jsch.Packet	\
	org.vngx.jsch.PortWatcher	\
	org.vngx.jsch.proxy.AbstractProxy	\
	org.vngx.jsch.proxy.Proxy	\
	org.vngx.jsch.proxy.ProxyHTTP	\
	org.vngx.jsch.proxy.ProxySOCKS4	\
	org.vngx.jsch.proxy.ProxySOCKS5	\
	org.vngx.jsch.Request	\
	org.vngx.jsch.RequestAgentForwarding	\
	org.vngx.jsch.RequestEnv	\
	org.vngx.jsch.RequestExec	\
	org.vngx.jsch.RequestPtyReq	\
	org.vngx.jsch.RequestSftp	\
	org.vngx.jsch.RequestShell	\
	org.vngx.jsch.RequestSignal	\
	org.vngx.jsch.RequestSubsystem	\
	org.vngx.jsch.RequestWindowChange	\
	org.vngx.jsch.RequestX11	\
	org.vngx.jsch.Session	\
	org.vngx.jsch.SessionIO	\
	org.vngx.jsch.SftpATTRS	\
	org.vngx.jsch.SftpProgressMonitor	\
	org.vngx.jsch.UIKeyboardInteractive	\
	org.vngx.jsch.userauth.AuthCancelException	\
	org.vngx.jsch.userauth.GSSContext	\
	org.vngx.jsch.userauth.GSSContextKrb5	\
	org.vngx.jsch.userauth.Identity	\
	org.vngx.jsch.userauth.IdentityFile	\
	org.vngx.jsch.userauth.IdentityManager	\
	org.vngx.jsch.userauth.PartialAuthException	\
	org.vngx.jsch.userauth.UserAuth	\
	org.vngx.jsch.userauth.UserAuthGSSAPIWithMIC	\
	org.vngx.jsch.userauth.UserAuthKeyboardInteractive	\
	org.vngx.jsch.userauth.UserAuthNone	\
	org.vngx.jsch.userauth.UserAuthPassword	\
	org.vngx.jsch.userauth.UserAuthPublicKey	\
	org.vngx.jsch.UserInfo	\
	org.vngx.jsch.util.DataUtil	\
	org.vngx.jsch.util.HashedHostKey	\
	org.vngx.jsch.util.HostKey	\
	org.vngx.jsch.util.HostKeyRepository	\
	org.vngx.jsch.util.KeyPair	\
	org.vngx.jsch.util.KeyPairDSA	\
	org.vngx.jsch.util.KeyPairRSA	\
	org.vngx.jsch.util.KeyType	\
	org.vngx.jsch.util.KnownHosts	\
	org.vngx.jsch.util.Logger	\
	org.vngx.jsch.util.SocketFactory	\
	org.vngx.jsch.Util	\
	org.vngx.jsch.VersionExchange
